const { app } = require('electron');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { boot } = require('../lib/desktop-app.cjs');
const { run, waitReady } = require('../lib/self-check.cjs');
// Use software rendering for deterministic capture on headless/remote Windows hosts.
app.disableHardwareAcceleration();
(async () => {
  const profile = await fs.mkdtemp(path.join(os.tmpdir(), 'geoclock-check-'));
  const desktop = await boot({ profileDir: profile, show: false, root: path.resolve(__dirname, '..') });
  await run(desktop, path.resolve(__dirname, '../.verification'));
  const win = desktop.win;
  const result = await win.webContents.executeJavaScript(`(() => {
    const set = (id, value) => { document.getElementById(id).value = value; };
    const add = (name, lat, lon) => { set('gcw-name', name); set('gcw-latitude', lat); set('gcw-longitude', lon); document.getElementById('gcw-add-location').click(); };
    add('Invalid', 91, 0); const invalid = document.querySelectorAll('.gcw-mrow').length;
    add('Greenwich', 0, 0); add('Tokyo', 35.6762, 139.6503);
    const names = [...document.querySelectorAll('.gcw-mname')].map(e => e.value);
    return { invalid, names, stored: Object.keys(localStorage) };
  })()`);
  assert.equal(result.invalid, 0); assert.deepEqual(result.names, ['Greenwich', 'Tokyo']);
  win.webContents.reload();
  await new Promise(resolve => win.webContents.once('did-finish-load', resolve));
  await waitReady(win);
  assert.equal(await win.webContents.executeJavaScript("document.querySelectorAll('.gcw-mrow').length"), 2);
  await win.webContents.executeJavaScript("document.querySelector('.gcw-mname').value = 'Zero'; document.querySelector('.gcw-mname').dispatchEvent(new Event('change')); document.querySelectorAll('.gcw-x')[1].click();");
  assert.equal(await win.webContents.executeJavaScript("document.querySelectorAll('.gcw-mrow').length"), 1);
  assert.equal(await win.webContents.executeJavaScript("Boolean(document.querySelector('.gcp-root'))"), true);
  await win.webContents.executeJavaScript("document.querySelector('.gcp-toggle').click(); document.querySelector('.gcp-controls input[type=time]').value = '08:00'; document.querySelector('.gcp-controls input[type=time]').dispatchEvent(new Event('change'));");
  assert.equal(await win.webContents.executeJavaScript("JSON.parse(localStorage.getItem('geoclock.planner.v1')).workStart"), '08:00');
  win.show(); win.focus();
  await win.webContents.executeJavaScript("document.getElementById('stage').requestFullscreen()", true);
  assert.equal(await win.webContents.executeJavaScript("!!document.fullscreenElement"), true);
  await new Promise(resolve => setTimeout(resolve, 2000));
  const fullscreen = await win.webContents.executeJavaScript("(() => {const s=document.getElementById('stage'), f=document.querySelector('geo-clock-card').shadowRoot.querySelector('.frame');return {match:s.matches(':fullscreen'), stage:s.getBoundingClientRect().toJSON(), frame:f.getBoundingClientRect().toJSON()};})()");
  assert.equal(fullscreen.match, true);
  assert.equal(fullscreen.stage.y, 0);
  assert.ok(fullscreen.frame.width > 0 && fullscreen.frame.height <= fullscreen.stage.height);
  console.log('Fullscreen dimensions:', fullscreen.frame.width, fullscreen.frame.height);
  const svg = await win.webContents.executeJavaScript("document.querySelector('geo-clock-card').shadowRoot.querySelector('svg').getBoundingClientRect().toJSON()");
  assert.ok(svg.left >= -1 && svg.right <= fullscreen.stage.width + 1);
  assert.ok(await win.webContents.executeJavaScript("document.querySelector('geo-clock-card').getBoundingClientRect().width > 100"));
  const fullscreenCapture = await win.webContents.capturePage();
  await fs.writeFile(path.resolve(__dirname, '../.verification/fullscreen.png'), fullscreenCapture.toPNG());
  const pixels = fullscreenCapture.toBitmap();
  assert.ok(pixels.some((value, index) => index % 4 !== 3 && value !== 0), 'Fullscreen capture must contain visible clock pixels.');
  const exitVisible = () => win.webContents.executeJavaScript("(() => {const b=document.getElementById('fs-exit-btn'),s=getComputedStyle(b);return !b.hidden && s.opacity==='1' && s.pointerEvents==='auto';})()");
  await win.webContents.executeJavaScript("document.getElementById('stage').dispatchEvent(new PointerEvent('pointermove', {bubbles:true}))");
  await new Promise(resolve => setTimeout(resolve, 250));
  assert.equal(await exitVisible(), true);
  await new Promise(resolve => setTimeout(resolve, 3000));
  // Fresh map interaction resets the five-second countdown.
  await win.webContents.executeJavaScript("document.getElementById('stage').dispatchEvent(new PointerEvent('pointerdown', {bubbles:true}))");
  await new Promise(resolve => setTimeout(resolve, 3000));
  assert.equal(await exitVisible(), true);
  await new Promise(resolve => setTimeout(resolve, 2400));
  assert.equal(await win.webContents.executeJavaScript("getComputedStyle(document.getElementById('fs-exit-btn')).opacity"), '0');
  assert.equal(await win.webContents.executeJavaScript("getComputedStyle(document.getElementById('fs-exit-btn')).pointerEvents"), 'none');
  await win.webContents.executeJavaScript("document.getElementById('stage').dispatchEvent(new PointerEvent('pointermove', {bubbles:true}))");
  await new Promise(resolve => setTimeout(resolve, 250));
  assert.equal(await exitVisible(), true);
  await win.webContents.executeJavaScript("document.getElementById('fs-exit-btn').click()", true);
  for (let i = 0; i < 20 && await win.webContents.executeJavaScript('!!document.fullscreenElement'); i++) await new Promise(resolve => setTimeout(resolve, 100));
  assert.equal(await win.webContents.executeJavaScript('!!document.fullscreenElement'), false);
  assert.equal(await win.webContents.executeJavaScript("document.getElementById('fs-exit-btn').hidden"), true);
  // Legacy live-location config must be normalized before any geolocation loop.
  await win.webContents.executeJavaScript("localStorage.setItem('geoclock.webconfig.v1', JSON.stringify({center:'me', lon:12, markers:[{auto:true,label:'Live'}, {label:'Fixed',lat:0,lon:0}]})); history.replaceState(null,'','/index.html');");
  win.webContents.reload();
  await new Promise(resolve => win.webContents.once('did-finish-load', resolve));
  await waitReady(win);
  assert.deepEqual(await win.webContents.executeJavaScript("(() => {const c=JSON.parse(localStorage.getItem('geoclock.webconfig.v1'));return {center:c.center,markers:c.markers.map(m=>m.label)};})()"), { center: 'lon', markers: ['Fixed'] });
  const http = require('node:http');
  let hits = 0;
  const server = http.createServer((request, response) => { hits++; response.end('unexpected'); });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const probe = `http://127.0.0.1:${server.address().port}/`;
  await assert.rejects(desktop.session.fetch(probe));
  assert.equal(await win.webContents.executeJavaScript(`fetch(${JSON.stringify(probe)}).then(()=>false,()=>true)`), true);
  assert.equal(hits, 0); await new Promise(resolve => server.close(resolve));
  assert.equal(await win.webContents.executeJavaScript("new Promise(resolve => navigator.geolocation.getCurrentPosition(()=>resolve(false), e=>resolve(e.code===1)))"), true);
  assert.equal(await win.webContents.executeJavaScript("window.open('https://example.com/') === null"), true);
  // The shared panel retains its existing online UI when offline is omitted.
  const online = await win.webContents.executeJavaScript(`(async () => {
    document.querySelector('.gcw-panel').remove();
    const {initWebConfig}=await import('./shared/geoclock-webconfig.js');
    initWebConfig(document.querySelector('geo-clock-card'));
    return { me:[...document.querySelectorAll('.gcw-panel option')].some(e=>e.value==='me'), share:document.querySelector('.gcw-panel').textContent.includes('Copy share link'), manual:!!document.getElementById('gcw-add-location') };
  })()`);
  assert.deepEqual(online, { me: true, share: true, manual: false });
  await desktop.session.flushStorageData();
  win.close();
  const reopened = await desktop.createWindow();
  await waitReady(reopened);
  assert.equal(await reopened.webContents.executeJavaScript("document.querySelectorAll('.gcw-mrow').length"), 1);
  assert.equal(await reopened.webContents.executeJavaScript("JSON.parse(localStorage.getItem('geoclock.planner.v1')).workStart"), '08:00');
  const aboutLoaded = new Promise(resolve => reopened.webContents.once('did-finish-load', resolve));
  await reopened.webContents.executeJavaScript("document.querySelector('a[href=\"credits.html\"]').click()");
  await aboutLoaded;
  assert.equal(await reopened.webContents.executeJavaScript("document.querySelector('details pre').textContent.includes('Permission is hereby granted')"), true);
  assert.equal(await reopened.webContents.executeJavaScript("document.querySelector('a[href=\"LICENSE.txt\"]') === null"), true);
  const clockLoaded = new Promise(resolve => reopened.webContents.once('did-finish-load', resolve));
  await reopened.webContents.executeJavaScript("document.querySelector('a[href=\"index.html\"]').click()");
  await clockLoaded;
  await waitReady(reopened);
  await reopened.webContents.executeJavaScript("const cb=document.getElementById('gcw-remember');cb.checked=false;cb.dispatchEvent(new Event('change'))");
  assert.deepEqual(await reopened.webContents.executeJavaScript("['geoclock.webconfig.v1','geoclock.planner.v1'].map(k=>localStorage.getItem(k))"), [null, null]);
  await reopened.webContents.executeJavaScript("document.querySelector('.gcw-mname').value='Unsaved'; document.querySelector('.gcw-mname').dispatchEvent(new Event('change'))");
  assert.equal(await reopened.webContents.executeJavaScript("localStorage.getItem('geoclock.webconfig.v1')"), null);
  await desktop.session.flushStorageData();
  reopened.close();
  const optedOut = await desktop.createWindow();
  await waitReady(optedOut);
  assert.deepEqual(await optedOut.webContents.executeJavaScript("({remember:document.getElementById('gcw-remember').checked, config:localStorage.getItem('geoclock.webconfig.v1'), markers:document.querySelectorAll('.gcw-mrow').length})"), { remember: false, config: null, markers: 0 });
  await optedOut.webContents.executeJavaScript("const cb=document.getElementById('gcw-remember');cb.checked=true;cb.dispatchEvent(new Event('change'));document.getElementById('gcw-name').value='Kept';document.getElementById('gcw-latitude').value='0';document.getElementById('gcw-longitude').value='0';document.getElementById('gcw-add-location').click()");
  await desktop.session.flushStorageData();
  optedOut.close();
  const optedIn = await desktop.createWindow();
  await waitReady(optedIn);
  assert.deepEqual(await optedIn.webContents.executeJavaScript("({remember:document.getElementById('gcw-remember').checked, markers:[...document.querySelectorAll('.gcw-mname')].map(e=>e.value)})"), { remember: true, markers: ['Kept'] });
  console.log('PASS: local assets, sandbox, network denial, manual coordinates, persistence and opt-out, embedded license, planner, fullscreen and web regression.');
  optedIn.close();
  await desktop.session.clearStorageData();
  app.exit(0);
})().catch(error => { console.error(error); app.exit(1); });
